name: CI using Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Set up JDK 21"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4

      - name: "Build Project"
        run: gradle clean build

      - name: "Run Tests"
        run: gradle test
